#!/usr/bin/perl

$! = 2;

if($ARGV[0] eq '-t') {
    if($ARGV[1] eq '-cf') {
        die "Invalid config file: $!" unless -e $ARGV[2];
        exit 0;
    }
    elsif($ARGV[1] eq '-lf') {
        die "Invalid leases file: $!" unless -e $ARGV[2];
        exit 0;
    }
}
else {
    exit 254;
}

